// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio;

public partial class HorariosDisponibles
{
    public int id { get; set; }

    public DateTime? fecha { get; set; }

    public TimeSpan? hora_inicio { get; set; }

    public int? duracion { get; set; }

    public decimal? monto_base { get; set; }

    public virtual ICollection<Reservas> Reservas { get; set; } = new List<Reservas>();
}