// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio;

public partial class Reservas
{
    public int id { get; set; }

    public int? usuario_id { get; set; }

    public int? horario_id { get; set; }

    public string tipo_reserva { get; set; }

    public int? tiempo_reservado { get; set; }

    public decimal? monto_pagar { get; set; }

    public virtual HorariosDisponibles horario { get; set; }

    public virtual Usuarios usuario { get; set; }
}