// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dominio;

public partial class ReservaFLContext : DbContext
{
    public ReservaFLContext(DbContextOptions<ReservaFLContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HorariosDisponibles> HorariosDisponibles { get; set; }

    public virtual DbSet<Reservas> Reservas { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HorariosDisponibles>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Horarios__3213E83FCF68198A");

            entity.Property(e => e.fecha).HasColumnType("date");
            entity.Property(e => e.monto_base).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Reservas>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Reservas__3213E83F75E86BFE");

            entity.Property(e => e.monto_pagar).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.tipo_reserva)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.horario).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.horario_id)
                .HasConstraintName("FK__Reservas__horari__3C69FB99");

            entity.HasOne(d => d.usuario).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.usuario_id)
                .HasConstraintName("FK__Reservas__usuari__3B75D760");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Usuarios__3213E83F10D22C6D");

            entity.Property(e => e.contraseña)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.correo)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}